export * from './user.repository';
export * from './scholarship.repository';
export * from './application.repository';
export * from './saved-scholarship.repository';
export * from './scholarship-category.repository';
export * from './profile.repository';
export * from './student-profile.repository';
export * from './eligibility-criteria.repository';
export * from './repositories.module';
